version: '2'
services:
    jhipster619-app:
        image: jhipster619
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster619-mysql:3306/jhipster619?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster619-mysql:
        extends:
            file: mysql.yml
            service: jhipster619-mysql
